server:
    interface: 0.0.0.0
    port: 5335

    verbosity: 0

    do-ip4: yes
    do-ip6: no

    do-udp: yes
    do-tcp: yes

    prefer-ip6: no

    root-hints: "/etc/unbound/root.hints"
    auto-trust-anchor-file: "/var/lib/unbound/root.key"